### ISSUE TITLE
Windows load error

### ISSUE THREAD

**Issue by ccjalal** [davidwhogg/MagicCube#7]
I get the following error on trying to run from windows and python 3.

Traceback (most recent call last):
  File "cube_interactive.py", line 46, in <module>
    class Cube:
  File "cube_interactive.py", line 77, in Cube
    for theta in (np.pi / 2, -np.pi / 2)]
  File "cube_interactive.py", line 77, in <listcomp>
    for theta in (np.pi / 2, -np.pi / 2)]
NameError: name 'x' is not defined

**Comment by davidwhogg** [comment]
The only thing I know how to do is shine the @jakevdp symbol.

**Comment by jakevdp** [comment]
That's quite strange because ``x`` is defined on line 76, right above where the error says it's undefined.

**Comment by hs309** [comment]
I found out that the code worked with 2.7 but had the issue with Python 3.6. Have you guys solved the problem?

**Comment by hs309** [comment]
@jakevdp @davidwhogg  @ccjalal 
Solved. The issue occurred due to the difference between Python 2 and 3.

Solution:
File "cube_interactive.py", lines 76-79 

    rots = [Quaternion.from_v_theta(x, theta)
            for theta in (np.pi / 2, -np.pi / 2)]
    rots += [Quaternion.from_v_theta(y, theta)
             for theta in (np.pi / 2, -np.pi / 2, np.pi, 2 * np.pi)]
=>
    rots = [Quaternion.from_v_theta(x, np.pi / 2)]
    rots += [Quaternion.from_v_theta(x, -np.pi / 2)]

    for theta in (np.pi / 2, -np.pi / 2, np.pi, 2 * np.pi):
        rots += [Quaternion.from_v_theta(y, theta)]

File projection.py, line 160
    trans = range(1, dproj.ndim) + [0] => trans = list(range(1, dproj.ndim)) + [0]
