### ISSUE TITLE
Line 77, x is not defined error

### ISSUE THREAD

**Issue by pdeitel** [davidwhogg/MagicCube#9]
I downloaded the code and tried to run it. I am getting 

Traceback (most recent call last):
  File "code/cube_interactive.py", line 46, in <module>
    class Cube:
  File "code/cube_interactive.py", line 77, in Cube
    for theta in (np.pi / 2, -np.pi / 2)]
  File "code/cube_interactive.py", line 77, in <listcomp>
    for theta in (np.pi / 2, -np.pi / 2)]
NameError: name 'x' is not defined

Any idea why?

**Comment by cadrians** [comment]
Looks like you are trying to run the code in Python3.

You have to change the lines 77 and 79 to:

rots = [Quaternion.from_v_theta(np.eye(3)[0], theta)
            for theta in (np.pi / 2, -np.pi / 2)]
    rots += [Quaternion.from_v_theta(np.eye(3)[1], theta)
             for theta in (np.pi / 2, -np.pi / 2, np.pi, 2 * np.pi)]

Furthermore in file projection.py you have to change line 160 to:

trans = list(range(1, dproj.ndim)) + [0]

After these two changes the code runs fine.

I will try to commit the changes to the repository.

**Comment by cadrians** [comment]
See the fork https://github.com/cadrians/MagicCube

It runs fine in Python3.

**Comment by pdeitel** [comment]
Thank you. I did find those changes and make them. 

However, when I run this in ipython on a Mac, it does not respond to the key strokes to rotate edges. What backend do you use?

Interestingly, if I put it into a Jupyter Notebook it runs as expected—except that the 3D rotation by dragging the mouse is very slow to respond. 



On Jan 16, 2018, at 5:49 AM, Adrian <notifications@github.com> wrote:

Looks like you are trying to run the code in Python3.

You have to change the lines 77 and 79 to:

rots = [Quaternion.from_v_theta(np.eye(3)[0], theta)
for theta in (np.pi / 2, -np.pi / 2)]
rots += [Quaternion.from_v_theta(np.eye(3)[1], theta)
for theta in (np.pi / 2, -np.pi / 2, np.pi, 2 * np.pi)]

Furthermore in file projection.py you have to change line 160 to:

trans = list(range(1, dproj.ndim)) + [0]

After these two changes the code runs fine.

I will try to commit the changes to the repository.

**Comment by davidwhogg** [comment]
if it's fixed now, close this.
